name: Release NPM package

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      skipTag:
        type: boolean
        required: false
        default: false
      tagPrefix:
        type: string
        required: false
        default: v
    secrets:
      npmReleaseToken:
        required: true

jobs:
  release:
    name: Release a new version of NPM package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.npmReleaseToken }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0
          cache: npm

      - name: Setup NPM auth
        run: printf '%s\n' '@cthesigns:registry=https://npm.pkg.github.com/' '//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}' 'engine-strict=true' > ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        uses: phips28/gh-action-bump-version@v9.0.31
        env:
          GITHUB_TOKEN: ${{ secrets.npmReleaseToken }}
        with:
          version-type: ${{ inputs.version }}
          commit-message: '{{version}}'
          skip-tag: ${{ inputs.skipTag }}
          tag-prefix: ${{ inputs.tagPrefix }}

      - name: Publish
        run: npm publish
